az policy definition create --name "deploy-diag-setting-for-BastionHosts" --display-name "Deploy Diagnostic Settings for Bastion Hosts to Log Analytics workspace"  --rules "Apply-Diag-Settings-BastionHosts.json" --params "parameters.json" --management-group "400" --metadata "category=Monitoring"  --mode All 
az policy definition create --name "deploy-diag-setting-for-AutomationAccount" --display-name "Deploy Diagnostic Settings for Automation Account to Log Analytics workspace"  --rules "Apply-Diag-Settings-AutomationAccounts.json" --params "parameters.json" --management-group "400" --metadata "category=Monitoring"  --mode All  
az policy definition create --name "deploy-diag-setting-for-ExpressRouteCircuits" --display-name "Deploy Diagnostic Settings for Express Route Circuits to Log Analytics workspace"  --rules "Apply-Diag-Settings-ExpressRouteCircuits.json" --params "parameters.json" --management-group "400" --metadata "category=Monitoring"  --mode All 
az policy definition create --name "deploy-diag-setting-for-LoadBalancers" --display-name "Deploy Diagnostic Settings for Load Balancers Log Analytics workspace"  --rules "Apply-Diag-Settings-LoadBalancers.json" --params "parameters.json" --management-group "400" --metadata "category=Monitoring"  --mode All 
az policy definition create --name "deploy-diag-setting-for-NetworkInterfaces" --display-name "Deploy Diagnostic Settings for Network Interfaces to Log Analytics workspace"  --rules "Apply-Diag-Settings-NetworkInterfaces.json" --params "parameters.json" --management-group "400" --metadata "category=Monitoring"  --mode All 
az policy definition create --name "deploy-diag-setting-for-NetworkSecurityGroups" --display-name "Deploy Diagnostic Settings for Network Security Groups to Log Analytics workspace"  --rules "Apply-Diag-Settings-NetworkSecurityGroups.json" --params "parameters.json" --management-group "400" --metadata "category=Monitoring"  --mode All 
az policy definition create --name "deploy-diag-setting-for-PublicIPAddresses" --display-name "Deploy Diagnostic Settings for Public IP Addresses to Log Analytics workspace"  --rules "Apply-Diag-Settings-PublicIPAddresses.json" --params "parameters.json" --management-group "400" --metadata "category=Monitoring"  --mode All 
az policy definition create --name "deploy-diag-setting-for-RecoveryServices" --display-name "Deploy Diagnostic Settings for Recovery Services to Log Analytics workspace"  --rules "Apply-Diag-Settings-RecoveryServices-vaults.json" --params "parameters.json" --management-group "400" --metadata "category=Monitoring"  --mode All 
az policy definition create --name "deploy-diag-setting-for-TrafficManagerProfiles" --display-name "Deploy Diagnostic Settings for Traffic Manager Profiles to Log Analytics workspace"  --rules "Apply-Diag-Settings-TrafficManagerProfiles.json" --params "parameters.json" --management-group "400" --metadata "category=Monitoring"  --mode All 
az policy definition create --name "deploy-diag-setting-for-StorageAccounts" --display-name "Deploy Diagnostic Settings for Storage Accounts to Log Analytics workspace"  --rules "Apply-Diag-Settings-StorageAccounts.json" --params "parameters.json" --management-group "400" --metadata "category=Monitoring"  --mode All 
az policy definition create --name "deploy-diag-setting-for-VirtualNetworks" --display-name "Deploy Diagnostic Settings for Virtual Networks to Log Analytics workspace"  --rules "Apply-Diag-Settings-VirtualNetworks.json" --params "parameters.json" --management-group "400" --metadata "category=Monitoring"  --mode All 
az policy definition create --name "deploy-diag-setting-for-ExpressRouteGateways" --display-name "Deploy Diagnostic Settings for Express Route Gateways to Log Analytics workspace"  --rules "Apply-Diag-Settings-ExpressRouteGateways.json" --params "parameters.json" --management-group "400" --metadata "category=Monitoring"  --mode All 
az policy definition create --name "deploy-diag-setting-for-VirtualMachines" --display-name "Deploy Diagnostic Settings for Virtual Machines to Log Analytics workspace"  --rules "Apply-Diag-Settings-VirtualMachines.json" --params "parameters.json" --management-group "400" --metadata "category=Monitoring"  --mode All 
az policy definition create --name "deploy-diag-setting-for-VpnGateways" --display-name "Deploy Diagnostic Settings for VPN Gateways to Log Analytics workspace"  --rules "Apply-Diag-Settings-VpnGateways.json" --params "parameters.json" --management-group "400" --metadata "category=Monitoring"  --mode All

